### ISSUE TITLE
User Story: Save sounds

### ISSUE THREAD

**Issue by lmariereese** [1907-cs-team-gladiators/dj-old-macdonald#14]
As a logged in user, I want to be able to save my wonderful sounds as a loop, so I can load/hear them again later.

- [x] react component save button #43 
- [x] IF LOGGED IN: Initial save of a new loop should show popup or form that asks the user to input a title for the loop 
- [x] IF NOT LOGGED IN: Clicking save should show popup that asks user to login or signup #86 
- [x] database model for loop (associated to user) #44
- [x] api routes (post) #45
- [x] redux action/action creator/thunk/reducer for saving a loop #46
- [x] API route (put) #92
