### ISSUE TITLE
User Story: Toggle sound 

### ISSUE THREAD

**Issue by lmariereese** [1907-cs-team-gladiators/dj-old-macdonald#16]
As a user, I want to be able to click on a grid/beat/input so that I can turn a sound on and off. 

Subtasks: 
- [x] Setup redux store #18 
- [x] Create Grid react component #19 
- [x] Create Row/Single Instrument react component #20
- [x] Create sound that plays each time a user presses a button #32

TO DO: 
- Setup Tone.js
